site_name: BayesJump
site_url: https://davidwalz@github.io/
site_author: David Walz
site_description: Mapping the space of Bayesian methods
# site_keywords: statistics, Bayesian methods, optimization, python
copyright: "Copyright &copy; 2020-2021 David Walz"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/DavidWalz
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/walzds
  analytics:
    provider: google
    property: UA-171268636-1

theme:
  name: "material"
  custom_dir: docs/overrides
  palette:
    primary: blue
  logo: images/favicon.ico
  favicon: images/favicon.ico
  features:
    - navigation.instant
    - search.suggest
    - search.highlight
    - toc.integrate  # integrate TOC in the navigation bar

plugins:
  - search
  - mkdocs-jupyter

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.tasklist

nav:
  - About: index.md
  - 2021:
    - posts/2021/wilkinson.ipynb
    - "Example .py post": posts/2021/example.py
    - posts/2021/move.md
  - 2020:
    - posts/2020/first-orchard.ipynb
    - posts/2020/pymoo.ipynb
    - posts/2020/bayesopt-frameworks.ipynb
    - posts/2020/bayesopt-acquisitions-single.ipynb
    - posts/2020/bayesopt-acquisitions-multi.ipynb
    - posts/2020/multiobjective-scalarization.ipynb
    - posts/2020/multiobjective-metrics.ipynb
    - posts/2020/pyrff.ipynb
    - posts/2020/karuba-junior.ipynb
    - posts/2020/gp-spectral-sampling.ipynb
    - posts/2020/gp-kernels.ipynb
