site_name: BayesJump
site_url: https://davidwalz@github.io/
site_author: David Walz
site_description: Mapping the space of Bayesian methods
# site_keywords: statistics, Bayesian methods, optimization, python 

copyright: "Copyright &copy; 2020-2021 David Walz"

nav:
  # - Intro: index.md
  - 2021:
    - "Example .py post": posts/2021/example.py
    - posts/2021/move.md
  - 2020:
    - posts/2020/first-orchard.ipynb
    - posts/2020/pymoo.ipynb
    - posts/2020/bayesopt-frameworks.ipynb
    - posts/2020/bayesopt-acquisitions-single.ipynb
    - posts/2020/bayesopt-acquisitions-multi.ipynb
    - posts/2020/multiobjective-scalarization.ipynb
    - posts/2020/multiobjective-metrics.ipynb
    - posts/2020/pyrff.ipynb
    - posts/2020/karuba-junior.ipynb
    - posts/2020/gp-spectral-sampling.ipynb
    - posts/2020/gp-kernels.ipynb

plugins:
  - search
  - mkdocs-jupyter

theme:
  name: "material"
  custom_dir: docs/overrides
  palette:
    primary: light blue
  logo: assets/favicon.ico
  favicon: assets/favicon.ico
  features:
    - navigation.instant
    # - navigation.tabs
    # - navigation.top
    # - header.autohide
    - search.suggest
    - search.highlight
